// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/pesterchum.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PesterService_Register_FullMethodName                = "/proto.PesterService/Register"
	PesterService_Login_FullMethodName                   = "/proto.PesterService/Login"
	PesterService_Logout_FullMethodName                  = "/proto.PesterService/Logout"
	PesterService_Validate_FullMethodName                = "/proto.PesterService/Validate"
	PesterService_GetUserData_FullMethodName             = "/proto.PesterService/GetUserData"
	PesterService_GetUserFriends_FullMethodName          = "/proto.PesterService/GetUserFriends"
	PesterService_GetFriendsRequests_FullMethodName      = "/proto.PesterService/GetFriendsRequests"
	PesterService_UpdateUsername_FullMethodName          = "/proto.PesterService/UpdateUsername"
	PesterService_UpdatePassword_FullMethodName          = "/proto.PesterService/UpdatePassword"
	PesterService_UpdatePhoto_FullMethodName             = "/proto.PesterService/UpdatePhoto"
	PesterService_UpdateDescription_FullMethodName       = "/proto.PesterService/UpdateDescription"
	PesterService_UpdateMood_FullMethodName              = "/proto.PesterService/UpdateMood"
	PesterService_UpdateColor_FullMethodName             = "/proto.PesterService/UpdateColor"
	PesterService_UpdateBirthdate_FullMethodName         = "/proto.PesterService/UpdateBirthdate"
	PesterService_UpdateAddress_FullMethodName           = "/proto.PesterService/UpdateAddress"
	PesterService_CreateRequestFriendship_FullMethodName = "/proto.PesterService/CreateRequestFriendship"
	PesterService_AnswerRequestFriendship_FullMethodName = "/proto.PesterService/AnswerRequestFriendship"
	PesterService_GetChatHistory_FullMethodName          = "/proto.PesterService/GetChatHistory"
	PesterService_SendMessage_FullMethodName             = "/proto.PesterService/SendMessage"
	PesterService_SubscribeChat_FullMethodName           = "/proto.PesterService/SubscribeChat"
	PesterService_GetPublicUserData_FullMethodName       = "/proto.PesterService/GetPublicUserData"
)

// PesterServiceClient is the client API for PesterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PesterServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Empty, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Validate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetUserData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUserDataResponse, error)
	GetUserFriends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUserFriendsResponse, error)
	GetFriendsRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFriendsRequestsList, error)
	UpdateUsername(ctx context.Context, in *UpdateUsernameRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateDescription(ctx context.Context, in *UpdateDescriptionRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateMood(ctx context.Context, in *UpdateMoodRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateColor(ctx context.Context, in *UpdateColorRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateBirthdate(ctx context.Context, in *UpdateBirthdateRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*Empty, error)
	CreateRequestFriendship(ctx context.Context, in *CreateRequestFriendshipRequest, opts ...grpc.CallOption) (*Empty, error)
	AnswerRequestFriendship(ctx context.Context, in *AnswerRequestFriendshipRequest, opts ...grpc.CallOption) (*Empty, error)
	GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	SubscribeChat(ctx context.Context, in *SubscribeChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	GetPublicUserData(ctx context.Context, in *GetPublicUserDataRequest, opts ...grpc.CallOption) (*GetPublicUserDataResponse, error)
}

type pesterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPesterServiceClient(cc grpc.ClientConnInterface) PesterServiceClient {
	return &pesterServiceClient{cc}
}

func (c *pesterServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, PesterService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) Logout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) Validate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) GetUserData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDataResponse)
	err := c.cc.Invoke(ctx, PesterService_GetUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) GetUserFriends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUserFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserFriendsResponse)
	err := c.cc.Invoke(ctx, PesterService_GetUserFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) GetFriendsRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFriendsRequestsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsRequestsList)
	err := c.cc.Invoke(ctx, PesterService_GetFriendsRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdateUsername(ctx context.Context, in *UpdateUsernameRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdateUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdatePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdateDescription(ctx context.Context, in *UpdateDescriptionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdateDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdateMood(ctx context.Context, in *UpdateMoodRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdateMood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdateColor(ctx context.Context, in *UpdateColorRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdateColor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdateBirthdate(ctx context.Context, in *UpdateBirthdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdateBirthdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_UpdateAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) CreateRequestFriendship(ctx context.Context, in *CreateRequestFriendshipRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_CreateRequestFriendship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) AnswerRequestFriendship(ctx context.Context, in *AnswerRequestFriendshipRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PesterService_AnswerRequestFriendship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatHistoryResponse)
	err := c.cc.Invoke(ctx, PesterService_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, PesterService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pesterServiceClient) SubscribeChat(ctx context.Context, in *SubscribeChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PesterService_ServiceDesc.Streams[0], PesterService_SubscribeChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PesterService_SubscribeChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *pesterServiceClient) GetPublicUserData(ctx context.Context, in *GetPublicUserDataRequest, opts ...grpc.CallOption) (*GetPublicUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicUserDataResponse)
	err := c.cc.Invoke(ctx, PesterService_GetPublicUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PesterServiceServer is the server API for PesterService service.
// All implementations must embed UnimplementedPesterServiceServer
// for forward compatibility.
type PesterServiceServer interface {
	Register(context.Context, *RegisterRequest) (*Empty, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *Empty) (*Empty, error)
	Validate(context.Context, *Empty) (*Empty, error)
	GetUserData(context.Context, *Empty) (*GetUserDataResponse, error)
	GetUserFriends(context.Context, *Empty) (*GetUserFriendsResponse, error)
	GetFriendsRequests(context.Context, *Empty) (*GetFriendsRequestsList, error)
	UpdateUsername(context.Context, *UpdateUsernameRequest) (*Empty, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*Empty, error)
	UpdatePhoto(context.Context, *UpdatePhotoRequest) (*Empty, error)
	UpdateDescription(context.Context, *UpdateDescriptionRequest) (*Empty, error)
	UpdateMood(context.Context, *UpdateMoodRequest) (*Empty, error)
	UpdateColor(context.Context, *UpdateColorRequest) (*Empty, error)
	UpdateBirthdate(context.Context, *UpdateBirthdateRequest) (*Empty, error)
	UpdateAddress(context.Context, *UpdateAddressRequest) (*Empty, error)
	CreateRequestFriendship(context.Context, *CreateRequestFriendshipRequest) (*Empty, error)
	AnswerRequestFriendship(context.Context, *AnswerRequestFriendshipRequest) (*Empty, error)
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	SubscribeChat(*SubscribeChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	GetPublicUserData(context.Context, *GetPublicUserDataRequest) (*GetPublicUserDataResponse, error)
	mustEmbedUnimplementedPesterServiceServer()
}

// UnimplementedPesterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPesterServiceServer struct{}

func (UnimplementedPesterServiceServer) Register(context.Context, *RegisterRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPesterServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPesterServiceServer) Logout(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedPesterServiceServer) Validate(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedPesterServiceServer) GetUserData(context.Context, *Empty) (*GetUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserData not implemented")
}
func (UnimplementedPesterServiceServer) GetUserFriends(context.Context, *Empty) (*GetUserFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserFriends not implemented")
}
func (UnimplementedPesterServiceServer) GetFriendsRequests(context.Context, *Empty) (*GetFriendsRequestsList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendsRequests not implemented")
}
func (UnimplementedPesterServiceServer) UpdateUsername(context.Context, *UpdateUsernameRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUsername not implemented")
}
func (UnimplementedPesterServiceServer) UpdatePassword(context.Context, *UpdatePasswordRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedPesterServiceServer) UpdatePhoto(context.Context, *UpdatePhotoRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePhoto not implemented")
}
func (UnimplementedPesterServiceServer) UpdateDescription(context.Context, *UpdateDescriptionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDescription not implemented")
}
func (UnimplementedPesterServiceServer) UpdateMood(context.Context, *UpdateMoodRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMood not implemented")
}
func (UnimplementedPesterServiceServer) UpdateColor(context.Context, *UpdateColorRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateColor not implemented")
}
func (UnimplementedPesterServiceServer) UpdateBirthdate(context.Context, *UpdateBirthdateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBirthdate not implemented")
}
func (UnimplementedPesterServiceServer) UpdateAddress(context.Context, *UpdateAddressRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAddress not implemented")
}
func (UnimplementedPesterServiceServer) CreateRequestFriendship(context.Context, *CreateRequestFriendshipRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRequestFriendship not implemented")
}
func (UnimplementedPesterServiceServer) AnswerRequestFriendship(context.Context, *AnswerRequestFriendshipRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerRequestFriendship not implemented")
}
func (UnimplementedPesterServiceServer) GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedPesterServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedPesterServiceServer) SubscribeChat(*SubscribeChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeChat not implemented")
}
func (UnimplementedPesterServiceServer) GetPublicUserData(context.Context, *GetPublicUserDataRequest) (*GetPublicUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicUserData not implemented")
}
func (UnimplementedPesterServiceServer) mustEmbedUnimplementedPesterServiceServer() {}
func (UnimplementedPesterServiceServer) testEmbeddedByValue()                       {}

// UnsafePesterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PesterServiceServer will
// result in compilation errors.
type UnsafePesterServiceServer interface {
	mustEmbedUnimplementedPesterServiceServer()
}

func RegisterPesterServiceServer(s grpc.ServiceRegistrar, srv PesterServiceServer) {
	// If the following call panics, it indicates UnimplementedPesterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PesterService_ServiceDesc, srv)
}

func _PesterService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).Logout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).Validate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_GetUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).GetUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_GetUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).GetUserData(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_GetUserFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).GetUserFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_GetUserFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).GetUserFriends(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_GetFriendsRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).GetFriendsRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_GetFriendsRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).GetFriendsRequests(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdateUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdateUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdateUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdateUsername(ctx, req.(*UpdateUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdatePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdatePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdatePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdatePhoto(ctx, req.(*UpdatePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdateDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdateDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdateDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdateDescription(ctx, req.(*UpdateDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdateMood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdateMood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdateMood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdateMood(ctx, req.(*UpdateMoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdateColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdateColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdateColor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdateColor(ctx, req.(*UpdateColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdateBirthdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBirthdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdateBirthdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdateBirthdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdateBirthdate(ctx, req.(*UpdateBirthdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_UpdateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).UpdateAddress(ctx, req.(*UpdateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_CreateRequestFriendship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequestFriendshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).CreateRequestFriendship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_CreateRequestFriendship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).CreateRequestFriendship(ctx, req.(*CreateRequestFriendshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_AnswerRequestFriendship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequestFriendshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).AnswerRequestFriendship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_AnswerRequestFriendship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).AnswerRequestFriendship(ctx, req.(*AnswerRequestFriendshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).GetChatHistory(ctx, req.(*GetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PesterService_SubscribeChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PesterServiceServer).SubscribeChat(m, &grpc.GenericServerStream[SubscribeChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PesterService_SubscribeChatServer = grpc.ServerStreamingServer[ChatEvent]

func _PesterService_GetPublicUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesterServiceServer).GetPublicUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PesterService_GetPublicUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesterServiceServer).GetPublicUserData(ctx, req.(*GetPublicUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PesterService_ServiceDesc is the grpc.ServiceDesc for PesterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PesterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PesterService",
	HandlerType: (*PesterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PesterService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PesterService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PesterService_Logout_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _PesterService_Validate_Handler,
		},
		{
			MethodName: "GetUserData",
			Handler:    _PesterService_GetUserData_Handler,
		},
		{
			MethodName: "GetUserFriends",
			Handler:    _PesterService_GetUserFriends_Handler,
		},
		{
			MethodName: "GetFriendsRequests",
			Handler:    _PesterService_GetFriendsRequests_Handler,
		},
		{
			MethodName: "UpdateUsername",
			Handler:    _PesterService_UpdateUsername_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _PesterService_UpdatePassword_Handler,
		},
		{
			MethodName: "UpdatePhoto",
			Handler:    _PesterService_UpdatePhoto_Handler,
		},
		{
			MethodName: "UpdateDescription",
			Handler:    _PesterService_UpdateDescription_Handler,
		},
		{
			MethodName: "UpdateMood",
			Handler:    _PesterService_UpdateMood_Handler,
		},
		{
			MethodName: "UpdateColor",
			Handler:    _PesterService_UpdateColor_Handler,
		},
		{
			MethodName: "UpdateBirthdate",
			Handler:    _PesterService_UpdateBirthdate_Handler,
		},
		{
			MethodName: "UpdateAddress",
			Handler:    _PesterService_UpdateAddress_Handler,
		},
		{
			MethodName: "CreateRequestFriendship",
			Handler:    _PesterService_CreateRequestFriendship_Handler,
		},
		{
			MethodName: "AnswerRequestFriendship",
			Handler:    _PesterService_AnswerRequestFriendship_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _PesterService_GetChatHistory_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _PesterService_SendMessage_Handler,
		},
		{
			MethodName: "GetPublicUserData",
			Handler:    _PesterService_GetPublicUserData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeChat",
			Handler:       _PesterService_SubscribeChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/pesterchum.proto",
}
