// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasSession() {
  return window['go']['auth']['AuthService']['HasSession']();
}

export function Login(arg1, arg2) {
  return window['go']['auth']['AuthService']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['auth']['AuthService']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['auth']['AuthService']['Register'](arg1, arg2);
}
