// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMood() {
  return window['go']['auth']['AuthService']['GetMood']();
}

export function GetUsername() {
  return window['go']['auth']['AuthService']['GetUsername']();
}

export function HasSession() {
  return window['go']['auth']['AuthService']['HasSession']();
}

export function Login(arg1, arg2) {
  return window['go']['auth']['AuthService']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['auth']['AuthService']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['auth']['AuthService']['Register'](arg1, arg2);
}

export function UpdateMood(arg1) {
  return window['go']['auth']['AuthService']['UpdateMood'](arg1);
}

export function UpdateUsername(arg1) {
  return window['go']['auth']['AuthService']['UpdateUsername'](arg1);
}
