// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function GetUserData():Promise<auth.UserData>;

export function HasSession():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function UpdateMood(arg1:string):Promise<void>;

export function UpdateUsername(arg1:string):Promise<void>;
