// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function AnswerFriendRequest(arg1:string,arg2:boolean):Promise<void>;

export function CreateFriendRequest(arg1:string):Promise<void>;

export function GetFriendsRequests():Promise<Array<auth.FriendRequest>>;

export function GetUserData():Promise<auth.UserData>;

export function GetUserFriends():Promise<Array<auth.Friend>>;

export function HasSession():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function UpdateAddress(arg1:string):Promise<void>;

export function UpdateBirthdate(arg1:string):Promise<void>;

export function UpdateColor(arg1:string):Promise<void>;

export function UpdateDescription(arg1:string):Promise<void>;

export function UpdateMood(arg1:string):Promise<void>;

export function UpdateUsername(arg1:string):Promise<void>;
