// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserData() {
  return window['go']['auth']['Service']['GetUserData']();
}

export function HasSession() {
  return window['go']['auth']['Service']['HasSession']();
}

export function Login(arg1, arg2) {
  return window['go']['auth']['Service']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['auth']['Service']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['auth']['Service']['Register'](arg1, arg2);
}

export function UpdateMood(arg1) {
  return window['go']['auth']['Service']['UpdateMood'](arg1);
}

export function UpdateUsername(arg1) {
  return window['go']['auth']['Service']['UpdateUsername'](arg1);
}
