// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerFriendRequest(arg1, arg2) {
  return window['go']['auth']['Service']['AnswerFriendRequest'](arg1, arg2);
}

export function CreateFriendRequest(arg1) {
  return window['go']['auth']['Service']['CreateFriendRequest'](arg1);
}

export function GetFriendsRequests() {
  return window['go']['auth']['Service']['GetFriendsRequests']();
}

export function GetUserData() {
  return window['go']['auth']['Service']['GetUserData']();
}

export function GetUserFriends() {
  return window['go']['auth']['Service']['GetUserFriends']();
}

export function HasSession() {
  return window['go']['auth']['Service']['HasSession']();
}

export function Login(arg1, arg2) {
  return window['go']['auth']['Service']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['auth']['Service']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['auth']['Service']['Register'](arg1, arg2);
}

export function UpdateAddress(arg1) {
  return window['go']['auth']['Service']['UpdateAddress'](arg1);
}

export function UpdateBirthdate(arg1) {
  return window['go']['auth']['Service']['UpdateBirthdate'](arg1);
}

export function UpdateColor(arg1) {
  return window['go']['auth']['Service']['UpdateColor'](arg1);
}

export function UpdateDescription(arg1) {
  return window['go']['auth']['Service']['UpdateDescription'](arg1);
}

export function UpdateMood(arg1) {
  return window['go']['auth']['Service']['UpdateMood'](arg1);
}

export function UpdateUsername(arg1) {
  return window['go']['auth']['Service']['UpdateUsername'](arg1);
}
