syntax = "proto3";

package proto;

option go_package = "/proto;proto";

service ChatService {
  rpc Register (RegisterRequest) returns (Empty);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc Logout (Empty) returns (Empty);
  rpc Validate (Empty) returns (Empty);

  rpc GetUserData (Empty) returns (GetUserDataResponse);
  rpc GetUserFriends (Empty) returns (GetUserFriendsResponse);
  rpc GetFriendsRequests (Empty) returns (GetFriendsRequestsList);

  rpc UpdateUsername (UpdateUsernameRequest) returns (Empty);
  rpc UpdatePassword (UpdatePasswordRequest) returns (Empty);
  rpc UpdatePhoto (UpdatePhotoRequest) returns (Empty);
  rpc UpdateDescription (UpdateDescriptionRequest) returns (Empty);
  rpc UpdateMood (UpdateMoodRequest) returns (Empty);
  rpc UpdateColor (UpdateColorRequest) returns (Empty);
  rpc UpdateBirthdate (UpdateBirthdateRequest) returns (Empty);
  rpc UpdateAddress (UpdateAddressRequest) returns (Empty);

  rpc CreateRequestFriendship (CreateRequestFriendshipRequest) returns (Empty);
  rpc AnswerRequestFriendship (AnswerRequestFriendshipRequest) returns (Empty);
}

message GetUserDataResponse {
  string user_id = 1;
  string username = 2;
  string photo = 3;
  string description = 4;
  string mood = 5;
  string color = 6;
  string birthdate = 7;
  string address = 8;
}

message GetUserFriendsResponse {
  repeated Friend friends = 1;
}

message Friend {
  string friend_id = 1;
  string friend_name = 2;
  string friend_mood = 3;
}

message GetFriendsRequestsResponse {
  string user_id = 1;
  string user_name = 2;
}

message GetFriendsRequestsList {
  repeated GetFriendsRequestsResponse requests = 1;
}

message FriendRequest {
  string user_id = 1;
  string user_name = 2;
}

message RegisterRequest {
  string username = 1;
  string password = 2;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  string session_id = 1;
}

message CreateRequestFriendshipRequest {
  string request_friend_name = 1;
}

message AnswerRequestFriendshipRequest {
  string user_id = 1;
  bool accept = 2;
}

message UpdateUsernameRequest {
  string new_username = 1;
}

message UpdatePasswordRequest {
  string new_password = 1;
}

message UpdatePhotoRequest {
  string new_photo = 1;
}

message UpdateDescriptionRequest {
  string new_description = 1;
}

message UpdateMoodRequest {
  string new_mood = 1;
}

message UpdateColorRequest {
  string new_color = 1;
}

message UpdateBirthdateRequest {
  string new_birthdate = 1;
}

message UpdateAddressRequest {
  string new_address = 1;
}

message Empty {}
