// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Photo         string                 `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Mood          string                 `protobuf:"bytes,5,opt,name=mood,proto3" json:"mood,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Birthdate     string                 `protobuf:"bytes,7,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserDataResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserDataResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserDataResponse) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *GetUserDataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetUserDataResponse) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *GetUserDataResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *GetUserDataResponse) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *GetUserDataResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetUserFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*Friend              `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFriendsResponse) Reset() {
	*x = GetUserFriendsResponse{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFriendsResponse) ProtoMessage() {}

func (x *GetUserFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetUserFriendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserFriendsResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      string                 `protobuf:"bytes,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	FriendName    string                 `protobuf:"bytes,2,opt,name=friend_name,json=friendName,proto3" json:"friend_name,omitempty"`
	FriendMood    string                 `protobuf:"bytes,3,opt,name=friend_mood,json=friendMood,proto3" json:"friend_mood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *Friend) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *Friend) GetFriendName() string {
	if x != nil {
		return x.FriendName
	}
	return ""
}

func (x *Friend) GetFriendMood() string {
	if x != nil {
		return x.FriendMood
	}
	return ""
}

type GetFriendsRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequestsResponse) Reset() {
	*x = GetFriendsRequestsResponse{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequestsResponse) ProtoMessage() {}

func (x *GetFriendsRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendsRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetFriendsRequestsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFriendsRequestsResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetFriendsRequestsList struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Requests      []*GetFriendsRequestsResponse `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequestsList) Reset() {
	*x = GetFriendsRequestsList{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequestsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequestsList) ProtoMessage() {}

func (x *GetFriendsRequestsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequestsList.ProtoReflect.Descriptor instead.
func (*GetFriendsRequestsList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendsRequestsList) GetRequests() []*GetFriendsRequestsResponse {
	if x != nil {
		return x.Requests
	}
	return nil
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *FriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      string                 `protobuf:"bytes,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                 // 20–100
	BeforeMsgId   string                 `protobuf:"bytes,3,opt,name=before_msg_id,json=beforeMsgId,proto3" json:"before_msg_id,omitempty"` // для пагинации вверх
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatHistoryRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatHistoryRequest) GetBeforeMsgId() string {
	if x != nil {
		return x.BeforeMsgId
	}
	return ""
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SubscribeChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      string                 `protobuf:"bytes,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeChatRequest) Reset() {
	*x = SubscribeChatRequest{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeChatRequest) ProtoMessage() {}

func (x *SubscribeChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeChatRequest.ProtoReflect.Descriptor instead.
func (*SubscribeChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeChatRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatEvent_Message
	//	*ChatEvent_Typing
	//	*ChatEvent_Read
	Event         isChatEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *ChatEvent) GetEvent() isChatEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatEvent) GetMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatEvent) GetTyping() *TypingEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *ChatEvent) GetRead() *ReadEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatEvent_Read); ok {
			return x.Read
		}
	}
	return nil
}

type isChatEvent_Event interface {
	isChatEvent_Event()
}

type ChatEvent_Message struct {
	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ChatEvent_Typing struct {
	Typing *TypingEvent `protobuf:"bytes,2,opt,name=typing,proto3,oneof"`
}

type ChatEvent_Read struct {
	Read *ReadEvent `protobuf:"bytes,3,opt,name=read,proto3,oneof"`
}

func (*ChatEvent_Message) isChatEvent_Event() {}

func (*ChatEvent_Typing) isChatEvent_Event() {}

func (*ChatEvent_Read) isChatEvent_Event() {}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TypingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsTyping      bool                   `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingEvent) Reset() {
	*x = TypingEvent{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingEvent) ProtoMessage() {}

func (x *TypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingEvent.ProtoReflect.Descriptor instead.
func (*TypingEvent) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *TypingEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingEvent) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type ReadEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpToMessageId string                 `protobuf:"bytes,2,opt,name=up_to_message_id,json=upToMessageId,proto3" json:"up_to_message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEvent) Reset() {
	*x = ReadEvent{}
	mi := &file_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEvent) ProtoMessage() {}

func (x *ReadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEvent.ProtoReflect.Descriptor instead.
func (*ReadEvent) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *ReadEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadEvent) GetUpToMessageId() string {
	if x != nil {
		return x.UpToMessageId
	}
	return ""
}

type GetPublicUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicUserDataRequest) Reset() {
	*x = GetPublicUserDataRequest{}
	mi := &file_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicUserDataRequest) ProtoMessage() {}

func (x *GetPublicUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetPublicUserDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetPublicUserDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPublicUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicUserDataResponse) Reset() {
	*x = GetPublicUserDataResponse{}
	mi := &file_proto_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicUserDataResponse) ProtoMessage() {}

func (x *GetPublicUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetPublicUserDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *GetPublicUserDataResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetPublicUserDataResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{18}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{19}
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateRequestFriendshipRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestFriendName string                 `protobuf:"bytes,1,opt,name=request_friend_name,json=requestFriendName,proto3" json:"request_friend_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateRequestFriendshipRequest) Reset() {
	*x = CreateRequestFriendshipRequest{}
	mi := &file_proto_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestFriendshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestFriendshipRequest) ProtoMessage() {}

func (x *CreateRequestFriendshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestFriendshipRequest.ProtoReflect.Descriptor instead.
func (*CreateRequestFriendshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRequestFriendshipRequest) GetRequestFriendName() string {
	if x != nil {
		return x.RequestFriendName
	}
	return ""
}

type AnswerRequestFriendshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequestFriendshipRequest) Reset() {
	*x = AnswerRequestFriendshipRequest{}
	mi := &file_proto_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequestFriendshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequestFriendshipRequest) ProtoMessage() {}

func (x *AnswerRequestFriendshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequestFriendshipRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequestFriendshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{21}
}

func (x *AnswerRequestFriendshipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnswerRequestFriendshipRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewUsername   string                 `protobuf:"bytes,1,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_proto_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateUsernameRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPassword   string                 `protobuf:"bytes,1,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_proto_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{23}
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPhoto      string                 `protobuf:"bytes,1,opt,name=new_photo,json=newPhoto,proto3" json:"new_photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePhotoRequest) Reset() {
	*x = UpdatePhotoRequest{}
	mi := &file_proto_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhotoRequest) ProtoMessage() {}

func (x *UpdatePhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhotoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePhotoRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{24}
}

func (x *UpdatePhotoRequest) GetNewPhoto() string {
	if x != nil {
		return x.NewPhoto
	}
	return ""
}

type UpdateDescriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewDescription string                 `protobuf:"bytes,1,opt,name=new_description,json=newDescription,proto3" json:"new_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDescriptionRequest) Reset() {
	*x = UpdateDescriptionRequest{}
	mi := &file_proto_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDescriptionRequest) ProtoMessage() {}

func (x *UpdateDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDescriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateDescriptionRequest) GetNewDescription() string {
	if x != nil {
		return x.NewDescription
	}
	return ""
}

type UpdateMoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMood       string                 `protobuf:"bytes,1,opt,name=new_mood,json=newMood,proto3" json:"new_mood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoodRequest) Reset() {
	*x = UpdateMoodRequest{}
	mi := &file_proto_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoodRequest) ProtoMessage() {}

func (x *UpdateMoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoodRequest.ProtoReflect.Descriptor instead.
func (*UpdateMoodRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateMoodRequest) GetNewMood() string {
	if x != nil {
		return x.NewMood
	}
	return ""
}

type UpdateColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewColor      string                 `protobuf:"bytes,1,opt,name=new_color,json=newColor,proto3" json:"new_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateColorRequest) Reset() {
	*x = UpdateColorRequest{}
	mi := &file_proto_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColorRequest) ProtoMessage() {}

func (x *UpdateColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColorRequest.ProtoReflect.Descriptor instead.
func (*UpdateColorRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateColorRequest) GetNewColor() string {
	if x != nil {
		return x.NewColor
	}
	return ""
}

type UpdateBirthdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewBirthdate  string                 `protobuf:"bytes,1,opt,name=new_birthdate,json=newBirthdate,proto3" json:"new_birthdate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBirthdateRequest) Reset() {
	*x = UpdateBirthdateRequest{}
	mi := &file_proto_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBirthdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBirthdateRequest) ProtoMessage() {}

func (x *UpdateBirthdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBirthdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateBirthdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateBirthdateRequest) GetNewBirthdate() string {
	if x != nil {
		return x.NewBirthdate
	}
	return ""
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewAddress    string                 `protobuf:"bytes,1,opt,name=new_address,json=newAddress,proto3" json:"new_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_proto_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateAddressRequest) GetNewAddress() string {
	if x != nil {
		return x.NewAddress
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{30}
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\x12\x05proto\"\xe4\x01\n" +
	"\x13GetUserDataResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05photo\x18\x03 \x01(\tR\x05photo\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04mood\x18\x05 \x01(\tR\x04mood\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x1c\n" +
	"\tbirthdate\x18\a \x01(\tR\tbirthdate\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\"A\n" +
	"\x16GetUserFriendsResponse\x12'\n" +
	"\afriends\x18\x01 \x03(\v2\r.proto.FriendR\afriends\"g\n" +
	"\x06Friend\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\tR\bfriendId\x12\x1f\n" +
	"\vfriend_name\x18\x02 \x01(\tR\n" +
	"friendName\x12\x1f\n" +
	"\vfriend_mood\x18\x03 \x01(\tR\n" +
	"friendMood\"R\n" +
	"\x1aGetFriendsRequestsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"W\n" +
	"\x16GetFriendsRequestsList\x12=\n" +
	"\brequests\x18\x01 \x03(\v2!.proto.GetFriendsRequestsResponseR\brequests\"E\n" +
	"\rFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"n\n" +
	"\x15GetChatHistoryRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\tR\bfriendId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\"\n" +
	"\rbefore_msg_id\x18\x03 \x01(\tR\vbeforeMsgId\"H\n" +
	"\x16GetChatHistoryResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.proto.ChatMessageR\bmessages\"K\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"S\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\"3\n" +
	"\x14SubscribeChatRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\tR\bfriendId\"\x9a\x01\n" +
	"\tChatEvent\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x12.proto.ChatMessageH\x00R\amessage\x12,\n" +
	"\x06typing\x18\x02 \x01(\v2\x12.proto.TypingEventH\x00R\x06typing\x12&\n" +
	"\x04read\x18\x03 \x01(\v2\x10.proto.ReadEventH\x00R\x04readB\a\n" +
	"\x05event\"\x9f\x01\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\tR\vrecipientId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"C\n" +
	"\vTypingEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_typing\x18\x02 \x01(\bR\bisTyping\"M\n" +
	"\tReadEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x10up_to_message_id\x18\x02 \x01(\tR\rupToMessageId\"3\n" +
	"\x18GetPublicUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x19GetPublicUserDataResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\".\n" +
	"\rLoginResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"P\n" +
	"\x1eCreateRequestFriendshipRequest\x12.\n" +
	"\x13request_friend_name\x18\x01 \x01(\tR\x11requestFriendName\"Q\n" +
	"\x1eAnswerRequestFriendshipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\":\n" +
	"\x15UpdateUsernameRequest\x12!\n" +
	"\fnew_username\x18\x01 \x01(\tR\vnewUsername\":\n" +
	"\x15UpdatePasswordRequest\x12!\n" +
	"\fnew_password\x18\x01 \x01(\tR\vnewPassword\"1\n" +
	"\x12UpdatePhotoRequest\x12\x1b\n" +
	"\tnew_photo\x18\x01 \x01(\tR\bnewPhoto\"C\n" +
	"\x18UpdateDescriptionRequest\x12'\n" +
	"\x0fnew_description\x18\x01 \x01(\tR\x0enewDescription\".\n" +
	"\x11UpdateMoodRequest\x12\x19\n" +
	"\bnew_mood\x18\x01 \x01(\tR\anewMood\"1\n" +
	"\x12UpdateColorRequest\x12\x1b\n" +
	"\tnew_color\x18\x01 \x01(\tR\bnewColor\"=\n" +
	"\x16UpdateBirthdateRequest\x12#\n" +
	"\rnew_birthdate\x18\x01 \x01(\tR\fnewBirthdate\"7\n" +
	"\x14UpdateAddressRequest\x12\x1f\n" +
	"\vnew_address\x18\x01 \x01(\tR\n" +
	"newAddress\"\a\n" +
	"\x05Empty2\xad\n" +
	"\n" +
	"\vChatService\x120\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\f.proto.Empty\x122\n" +
	"\x05Login\x12\x13.proto.LoginRequest\x1a\x14.proto.LoginResponse\x12$\n" +
	"\x06Logout\x12\f.proto.Empty\x1a\f.proto.Empty\x12&\n" +
	"\bValidate\x12\f.proto.Empty\x1a\f.proto.Empty\x127\n" +
	"\vGetUserData\x12\f.proto.Empty\x1a\x1a.proto.GetUserDataResponse\x12=\n" +
	"\x0eGetUserFriends\x12\f.proto.Empty\x1a\x1d.proto.GetUserFriendsResponse\x12A\n" +
	"\x12GetFriendsRequests\x12\f.proto.Empty\x1a\x1d.proto.GetFriendsRequestsList\x12<\n" +
	"\x0eUpdateUsername\x12\x1c.proto.UpdateUsernameRequest\x1a\f.proto.Empty\x12<\n" +
	"\x0eUpdatePassword\x12\x1c.proto.UpdatePasswordRequest\x1a\f.proto.Empty\x126\n" +
	"\vUpdatePhoto\x12\x19.proto.UpdatePhotoRequest\x1a\f.proto.Empty\x12B\n" +
	"\x11UpdateDescription\x12\x1f.proto.UpdateDescriptionRequest\x1a\f.proto.Empty\x124\n" +
	"\n" +
	"UpdateMood\x12\x18.proto.UpdateMoodRequest\x1a\f.proto.Empty\x126\n" +
	"\vUpdateColor\x12\x19.proto.UpdateColorRequest\x1a\f.proto.Empty\x12>\n" +
	"\x0fUpdateBirthdate\x12\x1d.proto.UpdateBirthdateRequest\x1a\f.proto.Empty\x12:\n" +
	"\rUpdateAddress\x12\x1b.proto.UpdateAddressRequest\x1a\f.proto.Empty\x12N\n" +
	"\x17CreateRequestFriendship\x12%.proto.CreateRequestFriendshipRequest\x1a\f.proto.Empty\x12N\n" +
	"\x17AnswerRequestFriendship\x12%.proto.AnswerRequestFriendshipRequest\x1a\f.proto.Empty\x12M\n" +
	"\x0eGetChatHistory\x12\x1c.proto.GetChatHistoryRequest\x1a\x1d.proto.GetChatHistoryResponse\x12D\n" +
	"\vSendMessage\x12\x19.proto.SendMessageRequest\x1a\x1a.proto.SendMessageResponse\x12@\n" +
	"\rSubscribeChat\x12\x1b.proto.SubscribeChatRequest\x1a\x10.proto.ChatEvent0\x01\x12V\n" +
	"\x11GetPublicUserData\x12\x1f.proto.GetPublicUserDataRequest\x1a .proto.GetPublicUserDataResponseB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_api_proto_goTypes = []any{
	(*GetUserDataResponse)(nil),            // 0: proto.GetUserDataResponse
	(*GetUserFriendsResponse)(nil),         // 1: proto.GetUserFriendsResponse
	(*Friend)(nil),                         // 2: proto.Friend
	(*GetFriendsRequestsResponse)(nil),     // 3: proto.GetFriendsRequestsResponse
	(*GetFriendsRequestsList)(nil),         // 4: proto.GetFriendsRequestsList
	(*FriendRequest)(nil),                  // 5: proto.FriendRequest
	(*GetChatHistoryRequest)(nil),          // 6: proto.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil),         // 7: proto.GetChatHistoryResponse
	(*SendMessageRequest)(nil),             // 8: proto.SendMessageRequest
	(*SendMessageResponse)(nil),            // 9: proto.SendMessageResponse
	(*SubscribeChatRequest)(nil),           // 10: proto.SubscribeChatRequest
	(*ChatEvent)(nil),                      // 11: proto.ChatEvent
	(*ChatMessage)(nil),                    // 12: proto.ChatMessage
	(*TypingEvent)(nil),                    // 13: proto.TypingEvent
	(*ReadEvent)(nil),                      // 14: proto.ReadEvent
	(*GetPublicUserDataRequest)(nil),       // 15: proto.GetPublicUserDataRequest
	(*GetPublicUserDataResponse)(nil),      // 16: proto.GetPublicUserDataResponse
	(*RegisterRequest)(nil),                // 17: proto.RegisterRequest
	(*LoginRequest)(nil),                   // 18: proto.LoginRequest
	(*LoginResponse)(nil),                  // 19: proto.LoginResponse
	(*CreateRequestFriendshipRequest)(nil), // 20: proto.CreateRequestFriendshipRequest
	(*AnswerRequestFriendshipRequest)(nil), // 21: proto.AnswerRequestFriendshipRequest
	(*UpdateUsernameRequest)(nil),          // 22: proto.UpdateUsernameRequest
	(*UpdatePasswordRequest)(nil),          // 23: proto.UpdatePasswordRequest
	(*UpdatePhotoRequest)(nil),             // 24: proto.UpdatePhotoRequest
	(*UpdateDescriptionRequest)(nil),       // 25: proto.UpdateDescriptionRequest
	(*UpdateMoodRequest)(nil),              // 26: proto.UpdateMoodRequest
	(*UpdateColorRequest)(nil),             // 27: proto.UpdateColorRequest
	(*UpdateBirthdateRequest)(nil),         // 28: proto.UpdateBirthdateRequest
	(*UpdateAddressRequest)(nil),           // 29: proto.UpdateAddressRequest
	(*Empty)(nil),                          // 30: proto.Empty
}
var file_proto_api_proto_depIdxs = []int32{
	2,  // 0: proto.GetUserFriendsResponse.friends:type_name -> proto.Friend
	3,  // 1: proto.GetFriendsRequestsList.requests:type_name -> proto.GetFriendsRequestsResponse
	12, // 2: proto.GetChatHistoryResponse.messages:type_name -> proto.ChatMessage
	12, // 3: proto.ChatEvent.message:type_name -> proto.ChatMessage
	13, // 4: proto.ChatEvent.typing:type_name -> proto.TypingEvent
	14, // 5: proto.ChatEvent.read:type_name -> proto.ReadEvent
	17, // 6: proto.ChatService.Register:input_type -> proto.RegisterRequest
	18, // 7: proto.ChatService.Login:input_type -> proto.LoginRequest
	30, // 8: proto.ChatService.Logout:input_type -> proto.Empty
	30, // 9: proto.ChatService.Validate:input_type -> proto.Empty
	30, // 10: proto.ChatService.GetUserData:input_type -> proto.Empty
	30, // 11: proto.ChatService.GetUserFriends:input_type -> proto.Empty
	30, // 12: proto.ChatService.GetFriendsRequests:input_type -> proto.Empty
	22, // 13: proto.ChatService.UpdateUsername:input_type -> proto.UpdateUsernameRequest
	23, // 14: proto.ChatService.UpdatePassword:input_type -> proto.UpdatePasswordRequest
	24, // 15: proto.ChatService.UpdatePhoto:input_type -> proto.UpdatePhotoRequest
	25, // 16: proto.ChatService.UpdateDescription:input_type -> proto.UpdateDescriptionRequest
	26, // 17: proto.ChatService.UpdateMood:input_type -> proto.UpdateMoodRequest
	27, // 18: proto.ChatService.UpdateColor:input_type -> proto.UpdateColorRequest
	28, // 19: proto.ChatService.UpdateBirthdate:input_type -> proto.UpdateBirthdateRequest
	29, // 20: proto.ChatService.UpdateAddress:input_type -> proto.UpdateAddressRequest
	20, // 21: proto.ChatService.CreateRequestFriendship:input_type -> proto.CreateRequestFriendshipRequest
	21, // 22: proto.ChatService.AnswerRequestFriendship:input_type -> proto.AnswerRequestFriendshipRequest
	6,  // 23: proto.ChatService.GetChatHistory:input_type -> proto.GetChatHistoryRequest
	8,  // 24: proto.ChatService.SendMessage:input_type -> proto.SendMessageRequest
	10, // 25: proto.ChatService.SubscribeChat:input_type -> proto.SubscribeChatRequest
	15, // 26: proto.ChatService.GetPublicUserData:input_type -> proto.GetPublicUserDataRequest
	30, // 27: proto.ChatService.Register:output_type -> proto.Empty
	19, // 28: proto.ChatService.Login:output_type -> proto.LoginResponse
	30, // 29: proto.ChatService.Logout:output_type -> proto.Empty
	30, // 30: proto.ChatService.Validate:output_type -> proto.Empty
	0,  // 31: proto.ChatService.GetUserData:output_type -> proto.GetUserDataResponse
	1,  // 32: proto.ChatService.GetUserFriends:output_type -> proto.GetUserFriendsResponse
	4,  // 33: proto.ChatService.GetFriendsRequests:output_type -> proto.GetFriendsRequestsList
	30, // 34: proto.ChatService.UpdateUsername:output_type -> proto.Empty
	30, // 35: proto.ChatService.UpdatePassword:output_type -> proto.Empty
	30, // 36: proto.ChatService.UpdatePhoto:output_type -> proto.Empty
	30, // 37: proto.ChatService.UpdateDescription:output_type -> proto.Empty
	30, // 38: proto.ChatService.UpdateMood:output_type -> proto.Empty
	30, // 39: proto.ChatService.UpdateColor:output_type -> proto.Empty
	30, // 40: proto.ChatService.UpdateBirthdate:output_type -> proto.Empty
	30, // 41: proto.ChatService.UpdateAddress:output_type -> proto.Empty
	30, // 42: proto.ChatService.CreateRequestFriendship:output_type -> proto.Empty
	30, // 43: proto.ChatService.AnswerRequestFriendship:output_type -> proto.Empty
	7,  // 44: proto.ChatService.GetChatHistory:output_type -> proto.GetChatHistoryResponse
	9,  // 45: proto.ChatService.SendMessage:output_type -> proto.SendMessageResponse
	11, // 46: proto.ChatService.SubscribeChat:output_type -> proto.ChatEvent
	16, // 47: proto.ChatService.GetPublicUserData:output_type -> proto.GetPublicUserDataResponse
	27, // [27:48] is the sub-list for method output_type
	6,  // [6:27] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	file_proto_api_proto_msgTypes[11].OneofWrappers = []any{
		(*ChatEvent_Message)(nil),
		(*ChatEvent_Typing)(nil),
		(*ChatEvent_Read)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
