// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Photo         string                 `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mood          string                 `protobuf:"bytes,4,opt,name=mood,proto3" json:"mood,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Birthdate     string                 `protobuf:"bytes,6,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserDataResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserDataResponse) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *GetUserDataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetUserDataResponse) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *GetUserDataResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *GetUserDataResponse) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *GetUserDataResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewUsername   string                 `protobuf:"bytes,1,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUsernameRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPassword   string                 `protobuf:"bytes,1,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPhoto      string                 `protobuf:"bytes,1,opt,name=new_photo,json=newPhoto,proto3" json:"new_photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePhotoRequest) Reset() {
	*x = UpdatePhotoRequest{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhotoRequest) ProtoMessage() {}

func (x *UpdatePhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhotoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePhotoRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePhotoRequest) GetNewPhoto() string {
	if x != nil {
		return x.NewPhoto
	}
	return ""
}

type UpdateDescriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewDescription string                 `protobuf:"bytes,1,opt,name=new_description,json=newDescription,proto3" json:"new_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDescriptionRequest) Reset() {
	*x = UpdateDescriptionRequest{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDescriptionRequest) ProtoMessage() {}

func (x *UpdateDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDescriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDescriptionRequest) GetNewDescription() string {
	if x != nil {
		return x.NewDescription
	}
	return ""
}

type UpdateMoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMood       string                 `protobuf:"bytes,1,opt,name=new_mood,json=newMood,proto3" json:"new_mood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoodRequest) Reset() {
	*x = UpdateMoodRequest{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoodRequest) ProtoMessage() {}

func (x *UpdateMoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoodRequest.ProtoReflect.Descriptor instead.
func (*UpdateMoodRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMoodRequest) GetNewMood() string {
	if x != nil {
		return x.NewMood
	}
	return ""
}

type UpdateColorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewColor      string                 `protobuf:"bytes,1,opt,name=new_color,json=newColor,proto3" json:"new_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateColorRequest) Reset() {
	*x = UpdateColorRequest{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColorRequest) ProtoMessage() {}

func (x *UpdateColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColorRequest.ProtoReflect.Descriptor instead.
func (*UpdateColorRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateColorRequest) GetNewColor() string {
	if x != nil {
		return x.NewColor
	}
	return ""
}

type UpdateBirthdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewBirthdate  string                 `protobuf:"bytes,1,opt,name=new_birthdate,json=newBirthdate,proto3" json:"new_birthdate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBirthdateRequest) Reset() {
	*x = UpdateBirthdateRequest{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBirthdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBirthdateRequest) ProtoMessage() {}

func (x *UpdateBirthdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBirthdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateBirthdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBirthdateRequest) GetNewBirthdate() string {
	if x != nil {
		return x.NewBirthdate
	}
	return ""
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewAddress    string                 `protobuf:"bytes,1,opt,name=new_address,json=newAddress,proto3" json:"new_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAddressRequest) GetNewAddress() string {
	if x != nil {
		return x.NewAddress
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\x12\x05proto\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\".\n" +
	"\rLoginResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xcb\x01\n" +
	"\x13GetUserDataResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05photo\x18\x02 \x01(\tR\x05photo\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04mood\x18\x04 \x01(\tR\x04mood\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x1c\n" +
	"\tbirthdate\x18\x06 \x01(\tR\tbirthdate\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\":\n" +
	"\x15UpdateUsernameRequest\x12!\n" +
	"\fnew_username\x18\x01 \x01(\tR\vnewUsername\":\n" +
	"\x15UpdatePasswordRequest\x12!\n" +
	"\fnew_password\x18\x01 \x01(\tR\vnewPassword\"1\n" +
	"\x12UpdatePhotoRequest\x12\x1b\n" +
	"\tnew_photo\x18\x01 \x01(\tR\bnewPhoto\"C\n" +
	"\x18UpdateDescriptionRequest\x12'\n" +
	"\x0fnew_description\x18\x01 \x01(\tR\x0enewDescription\".\n" +
	"\x11UpdateMoodRequest\x12\x19\n" +
	"\bnew_mood\x18\x01 \x01(\tR\anewMood\"1\n" +
	"\x12UpdateColorRequest\x12\x1b\n" +
	"\tnew_color\x18\x01 \x01(\tR\bnewColor\"=\n" +
	"\x16UpdateBirthdateRequest\x12#\n" +
	"\rnew_birthdate\x18\x01 \x01(\tR\fnewBirthdate\"7\n" +
	"\x14UpdateAddressRequest\x12\x1f\n" +
	"\vnew_address\x18\x01 \x01(\tR\n" +
	"newAddress\"\a\n" +
	"\x05Empty2\xdc\x05\n" +
	"\vChatService\x120\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\f.proto.Empty\x122\n" +
	"\x05Login\x12\x13.proto.LoginRequest\x1a\x14.proto.LoginResponse\x12$\n" +
	"\x06Logout\x12\f.proto.Empty\x1a\f.proto.Empty\x12&\n" +
	"\bValidate\x12\f.proto.Empty\x1a\f.proto.Empty\x127\n" +
	"\vGetUserData\x12\f.proto.Empty\x1a\x1a.proto.GetUserDataResponse\x12<\n" +
	"\x0eUpdateUsername\x12\x1c.proto.UpdateUsernameRequest\x1a\f.proto.Empty\x12<\n" +
	"\x0eUpdatePassword\x12\x1c.proto.UpdatePasswordRequest\x1a\f.proto.Empty\x126\n" +
	"\vUpdatePhoto\x12\x19.proto.UpdatePhotoRequest\x1a\f.proto.Empty\x12B\n" +
	"\x11UpdateDescription\x12\x1f.proto.UpdateDescriptionRequest\x1a\f.proto.Empty\x124\n" +
	"\n" +
	"UpdateMood\x12\x18.proto.UpdateMoodRequest\x1a\f.proto.Empty\x126\n" +
	"\vUpdateColor\x12\x19.proto.UpdateColorRequest\x1a\f.proto.Empty\x12>\n" +
	"\x0fUpdateBirthdate\x12\x1d.proto.UpdateBirthdateRequest\x1a\f.proto.Empty\x12:\n" +
	"\rUpdateAddress\x12\x1b.proto.UpdateAddressRequest\x1a\f.proto.EmptyB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_api_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: proto.RegisterRequest
	(*LoginRequest)(nil),             // 1: proto.LoginRequest
	(*LoginResponse)(nil),            // 2: proto.LoginResponse
	(*GetUserDataResponse)(nil),      // 3: proto.GetUserDataResponse
	(*UpdateUsernameRequest)(nil),    // 4: proto.UpdateUsernameRequest
	(*UpdatePasswordRequest)(nil),    // 5: proto.UpdatePasswordRequest
	(*UpdatePhotoRequest)(nil),       // 6: proto.UpdatePhotoRequest
	(*UpdateDescriptionRequest)(nil), // 7: proto.UpdateDescriptionRequest
	(*UpdateMoodRequest)(nil),        // 8: proto.UpdateMoodRequest
	(*UpdateColorRequest)(nil),       // 9: proto.UpdateColorRequest
	(*UpdateBirthdateRequest)(nil),   // 10: proto.UpdateBirthdateRequest
	(*UpdateAddressRequest)(nil),     // 11: proto.UpdateAddressRequest
	(*Empty)(nil),                    // 12: proto.Empty
}
var file_proto_api_proto_depIdxs = []int32{
	0,  // 0: proto.ChatService.Register:input_type -> proto.RegisterRequest
	1,  // 1: proto.ChatService.Login:input_type -> proto.LoginRequest
	12, // 2: proto.ChatService.Logout:input_type -> proto.Empty
	12, // 3: proto.ChatService.Validate:input_type -> proto.Empty
	12, // 4: proto.ChatService.GetUserData:input_type -> proto.Empty
	4,  // 5: proto.ChatService.UpdateUsername:input_type -> proto.UpdateUsernameRequest
	5,  // 6: proto.ChatService.UpdatePassword:input_type -> proto.UpdatePasswordRequest
	6,  // 7: proto.ChatService.UpdatePhoto:input_type -> proto.UpdatePhotoRequest
	7,  // 8: proto.ChatService.UpdateDescription:input_type -> proto.UpdateDescriptionRequest
	8,  // 9: proto.ChatService.UpdateMood:input_type -> proto.UpdateMoodRequest
	9,  // 10: proto.ChatService.UpdateColor:input_type -> proto.UpdateColorRequest
	10, // 11: proto.ChatService.UpdateBirthdate:input_type -> proto.UpdateBirthdateRequest
	11, // 12: proto.ChatService.UpdateAddress:input_type -> proto.UpdateAddressRequest
	12, // 13: proto.ChatService.Register:output_type -> proto.Empty
	2,  // 14: proto.ChatService.Login:output_type -> proto.LoginResponse
	12, // 15: proto.ChatService.Logout:output_type -> proto.Empty
	12, // 16: proto.ChatService.Validate:output_type -> proto.Empty
	3,  // 17: proto.ChatService.GetUserData:output_type -> proto.GetUserDataResponse
	12, // 18: proto.ChatService.UpdateUsername:output_type -> proto.Empty
	12, // 19: proto.ChatService.UpdatePassword:output_type -> proto.Empty
	12, // 20: proto.ChatService.UpdatePhoto:output_type -> proto.Empty
	12, // 21: proto.ChatService.UpdateDescription:output_type -> proto.Empty
	12, // 22: proto.ChatService.UpdateMood:output_type -> proto.Empty
	12, // 23: proto.ChatService.UpdateColor:output_type -> proto.Empty
	12, // 24: proto.ChatService.UpdateBirthdate:output_type -> proto.Empty
	12, // 25: proto.ChatService.UpdateAddress:output_type -> proto.Empty
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
